src/controllers/getters.py
from src.connections.escalationdb import connectToEscalationDB


def getAllTeams() -> list:
    query = ''' select * from teams 
            order by team_name asc
            '''
    conn = connectToEscalationDB()

    conn.execute(query)
    teams = conn.fetchall()
    conn.commit()
    conn.close()

    return teams

def getTeamNameByID (teamID: int) -> str:
    query = ''' select team_name from teams where team_id = {} '''.format(teamID)
    conn = connectToEscalationDB()

    conn.execute(query)
    teamName = conn.fetchone()
    conn.commit()
    conn.close()

    try:
        return teamName[0]
    except:
        return ""

def getUrlsByID(teamID) -> list:
    query = ''' select * from URLs 
            where team_id={}
            '''.format(teamID)
    conn = connectToEscalationDB()

    conn.execute(query)
    urls = conn.fetchall()
    conn.commit()
    conn.close()
    try:
        return urls
    except:
        return None

src/controllers/setters.py
from src.connections.escalationdb import connectToEscalationDB


def addUrl(URL_name:str, URL_link:str, team_id:int) -> bool:
    try:
        query = '''insert into URLs 
        (URL_name, URL_link, team_id)
        values ('{}', '{}', {})
        '''.format(URL_name, URL_link, team_id)
        conn = connectToEscalationDB()
        conn.execute(query)
        conn.commit()
        conn.close()
        return True
    except Exception as e:
        print(e)
        print("Erro ao adicionar URL")
        return False

def deleteUrlByID(URL_id):
    try:
        query = '''delete from URLs 
                where URL_id = {}
                '''.format(URL_id)
        conn = connectToEscalationDB()
        conn.execute(query)
        conn.commit()
        conn.close()
        return True
    except:
        print("Erro ao deletar URL")
        return False

src/routes/editRoutes.py
from flask import Blueprint, render_template, request, redirect, url_for
from src.controllers.getters import getTeamNameByID, getUrlsByID
from src.controllers.setters import addUrl, deleteUrlByID

editRoutes = Blueprint('edit', __name__, url_prefix='/edit')

@editRoutes.route("/equipes")
def edit():

    return render_template('editEquipes.html')

@editRoutes.route("/links/<teamID>", methods=["GET", "POST"])
def editLinks(teamID):
    if request.method == "POST":
        URL_id = request.form['URL_id']
        deleteUrlByID(URL_id)
    teamName = getTeamNameByID(teamID)
    urls = getUrlsByID(teamID)

    return render_template("editLinks.html", teamID=teamID, teamName=teamName, urls=urls)


@editRoutes.route("/links/<teamID>/add", methods=["GET", "POST"])
def addUrls(teamID):
    teamName = getTeamNameByID(teamID)
    if request.method=="POST":
        try:
            url = request.form
            addedUrl = addUrl(url["titulo"], url["url"], teamID)
            if addedUrl==True:
                return redirect(url_for('edit.editLinks', teamID=teamID))
            else:
                return render_template('addLinks.html',teamName=teamName, teamID=teamID, blockToShow="Erro")
        except Exception as e:
            print(e)
            return render_template('addLinks.html',teamName=teamName, teamID=teamID, blockToShow="Erro")

    return render_template("addLinks.html", teamName=teamName, teamID=teamID)

src/routes/viewRoutes.py
from flask import Blueprint, render_template, request
from src.controllers.getters import getTeamNameByID, getUrlsByID


viewRoutes = Blueprint('view', __name__, url_prefix='/view')


@viewRoutes.route("/equipes")
def getTeams():

    return render_template('equipes.html')


@viewRoutes.route("/links/<teamID>", methods=["GET", "POST"])
def getViewTeam(teamID):
    teamName = getTeamNameByID(teamID)
    urls = getUrlsByID(teamID)

    return render_template('links.html', teamID=teamID, teamName=teamName, urls=urls)

src/templates/addLinks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $('[data-toggle="popover"]').popover({
                placement : 'bottom',
                trigger : 'hover',
                html: true
            });
        });
    </script>
    <title>Add</title>
</head>
{% extends 'index.html' %}
{% block body %}
    <p class="titleName">{{teamName}}</p>

    {% if blockToShow == 'Erro' %}
    <div><h2 class="errorAlerts"> URL não cadastrado. </h2></div>
    {% endif %}
    <div class="backButton">
        <form action="/edit/links/{{teamID}}">
            <button> <img src="/static/img/icons8-left-24.png" alt="go-back"> </button>
        </form>
    </div>
    <div>
        <form action="/edit/links/{{teamID}}/add", method="post">
            <label for="url">Titulo da URL:</label>
                <input class="inputForm" type="text" name="titulo" placeholder="Título exemplo" required>
            <label for="url">URL:</label>
                <input class="inputForm" type="url" name="url" placeholder="https://exemplo.com.br" required>
                <img class="infoButton" src="/static/img/icons8-info-24.png" alt="info-button" data-toggle="popover" title="" data-content=" Necessário http:// ou https:// antes da URL.">
                <input class="button" type="submit" value="Salvar">
        </form>
    </div>
{% endblock %}
</html>

src/templates/editEquipes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Equipes</title>
</head>
{% extends 'index.html' %}
{% block body %}
    <div class="backButton">
        <form action="/">
            <button> <img src="/static/img/icons8-left-24.png" alt="go-back"> </button>
        </form>
    </div>
    <div>
        <table>
            <tbody>
                {% for team in allTeams %}
                    <tr>
                        <td><a href="{{url_for('edit.editLinks', teamID=team[0])}}">{{team[1]}}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
</html>

src/templates/editLinks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{teamName}}</title>
</head>
{% extends 'index.html' %}
{% block body %}
    <h2 class="titleName">{{teamName}}</h2>
    <div class="backButton">
        <form action="/edit/equipes">
            <button> <img src="/static/img/icons8-left-24.png" alt="go-back"> </button>
        </form>
    </div>
    <div>
        <table>
            <tbody>
                {% for url in urls %}
                <tr>
                    <td><a href="{{url[2]}}">{{url[1]}}</a></td>
                    <td>
                        <form action="", method="post">
                            <input style="display: none;" value="{{url[0]}}" name="URL_id">
                            <button class="button"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <form action="{{teamID}}/add">
            <button class="plusButton"><i class="fa fa-plus"></i></button>
        </form>
    </div>
{% endblock %}
</html>

src/templates/equipes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Equipes</title>
</head>
{% extends 'index.html' %}
{% block body %}
    <div class="backButton">
        <form action="/">
            <button> <img src="/static/img/icons8-left-24.png" alt="go-back"> </button>
        </form>
    </div>
    <ul>
        {% for team in allTeams %}
        <li><a href="{{url_for('view.getViewTeam', teamID=team[0])}}">{{team[1]}}</a></li>
        {% endfor %}
    </ul>
{% endblock %}
</html>

src/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
{% extends 'index.html' %}
{% block body %}
    <ul>
        <li><a href="http://10.100.59.10:70/">Escalações</a></li>
        <li><a href="{{url_for('view.getTeams')}}">Equipes</a></li>
    </ul>
{% endblock %}
</html>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/buttons.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Main</title>
</head>
<body>
    <div class="buttonsIndex">
        <a href="{{url_for('index')}}">
            <img src="/static/img/logo.png" alt="logo">
        </a>
    </div>
    <div class="body">

        {%block body %}{%endblock%}
    </div>
</body>
</html>

src/templates/links.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{teamName}}</title>
</head>
{% extends 'index.html' %}
{% block body %}
    <h2 class="titleName">{{teamName}}</h2>
    <div class="backButton">
        <form action="/view/equipes">
            <button> <img src="/static/img/icons8-left-24.png" alt="go-back"> </button>
        </form>
    </div>
    <div>
        <table>
            <tbody>
                {% for url in urls %}
                <tr>
                    <td><a href="{{url[2]}}">{{url[1]}}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
</html>